# --- Health Check ---
healthcheck_flask_url:    "http://127.0.0.1:{{ webapp_host_port }}/"
healthcheck_nginx_url:    "http://127.0.0.1:{{ nginx_host_port }}/"
healthcheck_timeout:      10
healthcheck_retries:      3
healthcheck_delay:        5
