[web]
node1 ansible_host=192.168.36.36
node2 ansible_host=192.168.36.37

[web:vars]
ansible_user=ubunu
ansible_ssh_pass='0'
ansible_become=true
ansible_become_method=sudo
ansible_become_pass='0'
ansible_python_interpreter=/usr/bin/python3
