[web]
node1 ansible_host=192.168.75.132
node2 ansible_host=192.168.75.133

[web:vars]
ansible_user=vagrant
ansible_ssh_pass='vagrant'
ansible_become=true
ansible_become_method=sudo
ansible_become_pass='vagrant'
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
